spring:
   profiles:
      active:
      - dev

---
spring:
   profiles: dev #开发环境
   application: 
      name: servicecloud-config-lmc-dev

---
spring:
   profiles: test #测试环境
   application: 
      name: servicecloud-config-lmc-test

# 必须保存为utf-8格式
